#!/usr/bin/env python

import os
import re
import sys
import shutil

# Written by:
# UPI: szhe560
# Name: Samuel Zheng
# UID:634715579

file_name = sys.argv[1]
version_number = sys.argv[2]
working_path = os.getcwd() + '/' + '.versiondir'
all_file_versions = os.listdir(working_path)
for file in all_file_versions:
    if re.search(file_name, file):
        if re.search(version_number, file[-1:]):
            if not re.search('swp', file):
                # code edited from https://stackoverflow.com/questions/39508469/reading-all-the-file-content-in-directory
                target_file = open(working_path + '/' + file_name)
                print target_file.read()
                target_file.close()