#!/usr/bin/env python

import os
import re
import shutil
import sys
import filecmp

# Written by:
# UPI: szhe560
# Name: Samuel Zheng
# UID:634715579

def main(file_name, version_number):
    target_files = []
    working_path = os.getcwd() + '/' + '.versiondir'
    same_version = False
    found_target_version = False

    all_file_versions = os.listdir(working_path)
    for file in all_file_versions:
        if re.search(file_name, file):
            target_files.extend([file])

    for target_file in target_files:
        if target_file[-1:] is str(version_number):
            found_target_version = True
            if not filecmp.cmp(working_path + '/' + target_file, working_path + '/' + file_name):
                shutil.copy(working_path + '/' + target_file, working_path + '/' + file_name)
            else:
                same_version = True

    if not found_target_version:
        print 'Version number ' + version_number + ' of file ' + file_name + ' does not exist.'
    elif same_version:
        print 'Version did not update because the current version and version ' + version_number + ' of ' + file_name + \
              'have identical contents'

    if (not same_version) and found_target_version:
        for index in range(6, 0, -1):
            for target_file in target_files:
                try:
                    if not re.search('swp', target_file):
                        if target_file[-1:] is str(index):
                            shutil.copy(working_path + '/' + target_file,
                                        working_path + '/' + target_file[:-1] + str(int(target_file[-1:]) + 1))
                except Exception as e:
                    continue

        target_files = get_files(file_name, working_path)

        for target_file in target_files:
            if target_files[-1:] is '7':
                os.remove(working_path + '/' + target_file)

        shutil.copy(working_path + '/' + file_name, working_path + '/' + file_name + '.1')


def get_files(file_name, working_path):
    target_files = []
    all_file_versions = os.listdir(working_path)
    for file in all_file_versions:
        if re.search(file_name, file):
            target_files.extend([file])
    return target_files


if __name__ == '__main__':
    # logging.basicConfig(level=logging.DEBUG)
    main(sys.argv[1], sys.argv[2])
