#!/usr/bin/env python

import logging

import os
import re

# Written by:
# UPI: szhe560
# Name: Samuel Zheng
# UID:634715579

def main():
    os.system("cd " + os.getcwd())
    os.system("rm .versiondir/*")
    os.system("rm -R .versiondir")
    os.system("fusermount -u mount")

if __name__ == '__main__':
    # logging.basicConfig(level=logging.DEBUG)
    main()